// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_data_access;

namespace backend_server.Migrations
{
    [DbContext(typeof(PicDbContext))]
    [Migration("20190323175857_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("backend_data_access.Model.MetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("backend_data_access.Model.MetaDataEntry", b =>
                {
                    b.Property<int>("MetaDataEntryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<int?>("MetaDataId");

                    b.Property<string>("Value");

                    b.Property<int>("type");

                    b.HasKey("MetaDataEntryId");

                    b.HasIndex("MetaDataId");

                    b.ToTable("MetaDataEntry");
                });

            modelBuilder.Entity("backend_data_access.Model.Photographer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Photographer");
                });

            modelBuilder.Entity("backend_data_access.Model.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FilePath");

                    b.Property<int?>("MetaDataId");

                    b.Property<string>("Name");

                    b.Property<int?>("PhotographerId");

                    b.HasKey("PictureId");

                    b.HasIndex("MetaDataId");

                    b.HasIndex("PhotographerId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("backend_data_access.Model.MetaDataEntry", b =>
                {
                    b.HasOne("backend_data_access.Model.MetaData")
                        .WithMany("data")
                        .HasForeignKey("MetaDataId");
                });

            modelBuilder.Entity("backend_data_access.Model.Picture", b =>
                {
                    b.HasOne("backend_data_access.Model.MetaData", "MetaData")
                        .WithMany()
                        .HasForeignKey("MetaDataId");

                    b.HasOne("backend_data_access.Model.Photographer", "Photographer")
                        .WithMany()
                        .HasForeignKey("PhotographerId");
                });
#pragma warning restore 612, 618
        }
    }
}
