// <auto-generated />

using System;
using backend_data_access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace backend_server.Migrations
{
    [DbContext(typeof(PicDbContext))]
    internal class PicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("backend_data_access.Model.MetaData", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.HasKey("Id");

                b.ToTable("Metadata");
            });

            modelBuilder.Entity("backend_data_access.Model.MetaDataEntry", b =>
            {
                b.Property<int>("MetaDataEntryId")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Key");

                b.Property<int?>("MetaDataId");

                b.Property<int>("Type");

                b.Property<string>("Value");

                b.HasKey("MetaDataEntryId");

                b.HasIndex("MetaDataId");

                b.ToTable("MetaDataEntry");
            });

            modelBuilder.Entity("backend_data_access.Model.Photographer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<DateTime>("Birthday");

                b.Property<string>("FirstName");

                b.Property<string>("LastName");

                b.Property<string>("Notes");

                b.HasKey("Id");

                b.ToTable("Photographer");
            });

            modelBuilder.Entity("backend_data_access.Model.Picture", b =>
            {
                b.Property<int>("PictureId")
                    .ValueGeneratedOnAdd();

                b.Property<string>("FilePath");

                b.Property<int>("MetaDataId");

                b.Property<int?>("PhotographerId");

                b.HasKey("PictureId");

                b.HasIndex("MetaDataId");

                b.HasIndex("PhotographerId");

                b.ToTable("Pictures");
            });

            modelBuilder.Entity("backend_data_access.Model.Tag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int?>("PictureId");

                b.Property<string>("Value");

                b.HasKey("Id");

                b.HasIndex("PictureId");

                b.ToTable("Tags");
            });

            modelBuilder.Entity("backend_data_access.Model.MetaDataEntry", b =>
            {
                b.HasOne("backend_data_access.Model.MetaData")
                    .WithMany("Data")
                    .HasForeignKey("MetaDataId");
            });

            modelBuilder.Entity("backend_data_access.Model.Picture", b =>
            {
                b.HasOne("backend_data_access.Model.MetaData", "MetaData")
                    .WithMany()
                    .HasForeignKey("MetaDataId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("backend_data_access.Model.Photographer", "Photographer")
                    .WithMany()
                    .HasForeignKey("PhotographerId");
            });

            modelBuilder.Entity("backend_data_access.Model.Tag", b =>
            {
                b.HasOne("backend_data_access.Model.Picture")
                    .WithMany("TagList")
                    .HasForeignKey("PictureId");
            });
#pragma warning restore 612, 618
        }
    }
}
